### ISSUE TITLE
hello everyone I am writing to report a problem regarding the Mupen64 emulator after the last update the games are jerky and are not fluid. can you solve this problem? thanks

### ISSUE THREAD

**Issue by Wesker92-max** [m64p/m64p#254] opened 2022-06-18 16:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]
 - GPU: [e.g. Intel HD 620]

**Additional context**

**Comment by loganmc10** [comment] 2022-06-19 01:08
Duplicate of https://github.com/m64p/m64p/issues/250

**Closed by loganmc10** 2022-06-19 01:08 UTC
