### ISSUE TITLE
Poor performance regardless of settings

### ISSUE THREAD

**Issue by Tinarg** [m64p/m64p#276] opened 2022-07-27 07:48 UTC
I've been using an older version of m64p for a little over a year now with almost no problems. Earlier today I decided to update from my February 2021 build to see if it'd fix a controller issue I was having. The bug is indeed fixed in the latest version of m64p, but the overall performance is now terrible.
It feels like there's a small correlation between the lag and the level of upscaling used, but aside from that it's consistent regardless of the settings available under Core and ParaLLEI Video.
I've tried updating my graphics drivers and forcing Windows to enable high-performance mode for m64p, but neither fixed the issue.
I also thought it might be some sort of caching issue, but the lag persists no matter how long you stay in an area.

Windows 10
Nvidia GTX 1070
Intel i7-6700K

(Enabling sound makes it easier to notice the slowdown)

https://user-images.githubusercontent.com/49109506/181187002-eb91a222-5324-44c5-9f1f-fa1d4a8da357.mp4

https://user-images.githubusercontent.com/49109506/181184626-0b3791f1-07db-48ec-aa0c-fce17c04d95b.mp4

*Footage from the Paper Mario randomizer

https://user-images.githubusercontent.com/49109506/181188501-e86c2302-c3f4-454e-a3b3-3d458e3960f9.mp4

**Comment by mistrk7** [comment] 2022-07-30 21:26
Same, have noticed performance issues as of the July builds. Noticable when launching SM64 and Mario shows his face.

**Comment by loganmc10** [comment] 2022-07-31 02:12
I'm going to close this as not a bug. The emulator is getting more accurate, and system requirements may increase as a result. Unless someone can point me to evidence of inefficient code somewhere, there isn't really anything I can look into to fix this.

@elektronicznypank your issue with Fighting Force is likely a legitimate bug. If the game shows 60FPS on the bottom right, but things aren't timed right in-game, it's probably a bug

**Closed by loganmc10** 2022-07-31 02:12 UTC
